apply plugin: 'java-library'
apply plugin: 'io.spring.dependency-management'

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:4.1.0"
    }
}

dependencies {
    api project(':queryecho-java-sdk')
    implementation project(':queryecho-http-transport')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-starter-aspectj'
    implementation 'org.springframework:spring-tx'
    compileOnly 'org.springframework:spring-webmvc'
    compileOnly 'jakarta.servlet:jakarta.servlet-api'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jdbc-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'com.h2database:h2'
}

java {
    withSourcesJar()
}
